GIFT_LIST = (
    ("JOGO_DE_PANELA", "Jogo de Panela"),
    ("JOGO_DE_XÍCARAS", "Jogo de Xícaras"),
    ("JOGO_DE_SOBREMESA", "Jogo de Sobremesa"),
    ("JOGO_DE_COPOS", "Jogo de Copos"),
    ("JOGO_DE_TAÇAS", "Jogo de Taças"),
    ("JOGO_DE_TALHERES", "Jogo de Talheres"),
    ("JOGO_DE_PRATOS", "Jogo de Pratos"),
    ("JOGO_DE_TRAVESSAS", "Jogo de Travessas"),
    ("KIT_FAQUEIRO", "Kit Faqueiro"),
    ("KIT_CHURRASQUEIRO", "Kit Churrasqueiro"),
    ("KIT_UTILIDADES", "Kit Utilidades"),
    ("SALADEIRA", "Saladeira"),
    ("FORMAS_DE_BOLO", "Formas de Bolo"),
    ("JARRAS_DE_VIDRO", "Jarras de Vidro"),
    ("TÁBUA_DE_CORTES", "Tábua de Cortes"),
    ("FRIGIDEIRAS", "Frigideiras"),
    ("SANDUICHEIRA", "Sanduicheira"),
    ("PORTA_DETERGENTE", "Porta Detergente"),
    ("PORTA_TEMPERO", "Porta Tempero"),
    ("ESCORREDOR_DE_LOUÇAS", "Escorredor de Louças"),
    ("VASILHAS", "Vasilhas"),
    ("LIQUIDIFICADOR", "Liquidificador"),
    ("BATEDEIRA", "Batedeira"),
    ("PANELA_DE_PRESSÃO", "Panela de Pressão"),
    ("GARRAFA_DE_CAFÉ", "Garrafa de Café"),
    ("PORTA_COPOS", "Porta Copos"),
    ("PORTA_FRIOS", "Porta Frios"),
    ("PORTA_BOLO", "Porta Bolo"),
    ("BANDEJAS", "Bandejas"),
    ("CUSCUZEIRA", "Cuscuzeira"),
    ("TAPETE_SALA", "Tapete Sala"),
    ("JOGO_DE_LENÇÓIS_C._BOX", "Jogo de Lençóis C. Box"),
    ("COBERTOR_CASAL", "Cobertor Casal"),
    ("MANTA_CASAL", "Manta Casal"),
    ("JOGO_DE_FRONHA", "Jogo de Fronha"),
    ("FORRO_DE_CAMA", "Forro de Cama"),
    ("CESTOS_ORGANIZADOR", "Cestos Organizador"),
    ("TRAVESSEIROS", "Travesseiros"),
    ("TOALHAS_DE_BANHO", "Toalhas de Banho"),
    ("JOGO_DE_BANHEIRO", "Jogo de Banheiro"),
    ("FERRO_DE_PASSAR", "Ferro de Passar"),
)
