# Generated by Django 5.1.5 on 2025-01-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
